// crates/desktop/src/routes/widget/+page.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import Pin from "@lucide/svelte/icons/pin";
  import PinOff from "@lucide/svelte/icons/pin-off";
  import X from "@lucide/svelte/icons/x";

  import { BatteryIndicator, DeviceArtwork, StatusMessage } from "$lib/components";
  import { backend } from "$lib/ipc";
  import { artworkFor } from "$lib/models";
  import { bluetooth, devices } from "$lib/stores";

  let hovered = $state(false);
  let pinned = $state(false);

  const artwork = $derived(artworkFor(devices.device?.model));

  onMount(async () => {
    pinned = await backend.isAlwaysOnTop();
  });

  async function togglePin() {
    pinned = !pinned;
    await backend.setAlwaysOnTop(pinned);
  }
</script>

<svelte:head>
  <title>winpods widget</title>
</svelte:head>

<!--
  `widget-root` is what tells `app.css` to keep the page background transparent, since this
  window is frameless and transparent and paints its own panel.

  `data-tauri-drag-region` makes the panel itself the window's drag handle.
-->
<div
  class="widget-root apple-glass relative flex h-screen w-screen flex-col overflow-hidden
         rounded-xl border border-white/10 bg-black/55 text-white"
  data-tauri-drag-region
  onmouseenter={() => (hovered = true)}
  onmouseleave={() => (hovered = false)}
  role="presentation"
>
  <!-- Window controls fade in on hover so they never obscure the readings. -->
  <div
    class="absolute top-1 right-1 z-10 flex items-center gap-0.5 transition-opacity duration-150"
    class:opacity-0={!hovered}
    class:pointer-events-none={!hovered}
  >
    <button
      onclick={togglePin}
      aria-label={pinned ? "Unpin widget" : "Pin widget on top"}
      class="rounded-md p-1.5 text-white/70 transition-colors hover:bg-white/15 hover:text-white"
    >
      {#if pinned}
        <PinOff class="size-3" aria-hidden="true" />
      {:else}
        <Pin class="size-3" aria-hidden="true" />
      {/if}
    </button>
    <button
      onclick={() => void backend.hideWindow()}
      aria-label="Hide widget"
      class="rounded-md p-1.5 text-white/70 transition-colors hover:bg-red-500/70 hover:text-white"
    >
      <X class="size-3.5" aria-hidden="true" />
    </button>
  </div>

  {#if !bluetooth.isOn}
    <StatusMessage
      icon="bluetooth-off"
      title="Bluetooth is off"
      message="Turn it on to see your device."
      onDark
    />
  {:else if !devices.device}
    <StatusMessage
      icon="headphones"
      title="No device selected"
      message="Pick one from the dashboard."
      onDark
    />
  {:else if !devices.isConnected}
    <StatusMessage
      icon="headphones"
      title={devices.device.name}
      message="Disconnected"
      onDark
    />
  {:else}
    <div
      class="flex min-h-0 flex-1 items-center justify-evenly gap-4 px-6"
      data-tauri-drag-region
    >
      <!-- Buds -->
      <div class="flex flex-col items-center gap-1.5">
        <DeviceArtwork model={devices.device.model} imgClass="h-11" />
        {#if devices.properties}
          <BatteryIndicator
            level={devices.overallLevel}
            charging={devices.isCharging}
            onDark
          />
        {:else}
          <span class="block h-3 w-14 animate-pulse rounded-full bg-white/20"></span>
        {/if}
      </div>

      <!-- Case, only for models that have one -->
      {#if artwork.case}
        <div class="flex flex-col items-center gap-1.5">
          <img
            src={artwork.case}
            alt="Charging case"
            class="h-11 w-auto object-contain"
          />
          {#if devices.properties}
            <BatteryIndicator
              level={devices.properties.caseBattery?.level ?? null}
              charging={devices.properties.caseBattery?.charging ?? false}
              onDark
            />
          {:else}
            <span class="block h-3 w-14 animate-pulse rounded-full bg-white/20"></span>
          {/if}
        </div>
      {/if}
    </div>
  {/if}
</div>

// crates/desktop/src/views/widget/index.vue
<script setup lang="ts">
import { Error } from "@/components";
import AirPodsImage from "@/components/AirPodsImage.vue";
import BatteryIcon from "@/components/BatteryIcon.vue";
import { getModelDetails } from "@/models";
import { useDevice } from "@/stores/device";
import { faThumbTack, faXmark } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import { computed } from "vue";

const connectedDeviceStore = useDevice();
const device = computed(() => connectedDeviceStore.device);
const deviceProperties = computed(() => connectedDeviceStore.deviceProperties);
const modelDetails = computed(() => getModelDetails(device.value?.model ?? "Unknown"));
const batteryLevel = computed(() => {
  const properties = deviceProperties.value;

  if (!properties) {
    return 0;
  }

  return Math.min(properties.leftBattery.level, properties.rightBattery.level);
});

const batteryCharging = computed(() => {
  const properties = deviceProperties.value;

  if (!properties) {
    return false;
  }

  return properties.leftBattery.charging && properties.rightBattery.charging;
});
</script>

<template>
  <div data-tauri-drag-region class="w-[300px] h-[125px] bg-black/40 text-white">
    <header class="absolute top-2 right-2 flex">
      <button class="cursor-pointer hover:bg-gray-700 rounded-full py-0.5 px-1">
        <FontAwesomeIcon size="xs" :icon="faThumbTack" />
      </button>
      <button class="cursor-pointer hover:bg-gray-700 rounded-full py-0.5 px-1.5">
        <FontAwesomeIcon size="sm" :icon="faXmark" />
      </button>
    </header>
    <template v-if="device">
      <main data-tauri-drag-region class="flex justify-around items-center h-full px-7">
        <div class="flex flex-col items-center gap-2">
          <AirPodsImage class="h-[50px]" :model="device.model" />
          <BatteryIcon :level="batteryLevel" :charging="batteryCharging" />
        </div>
        <div
          class="flex flex-col items-center gap-2"
          v-if="modelDetails.widget.caseImage"
        >
          <img
            class="h-[50px]"
            :src="modelDetails.widget.caseImage"
            :alt="`${device.model}-case`"
          />
          <BatteryIcon
            v-if="deviceProperties?.caseBattery"
            :level="deviceProperties.caseBattery.level"
            :charging="deviceProperties.caseBattery.charging"
          />
        </div>
      </main>
    </template>
    <Error
      data-tauri-drag-region
      v-else
      title="No Device Selected"
      message="Please select a device from dashboard to view its status."
    />
  </div>
</template>
