// crates/desktop/src/views/dashboard/pages/SettingsPage.vue
<script setup lang="ts">
import Switch from "@/components/Switch.vue";
import { useSettings } from "@/stores/settings";

const settings = useSettings();
const batteryThresholdOptions = [
  { value: 0, label: "Disabled" },
  ...Array.from({ length: 9 }, (_, i) => ({
    value: (i + 1) * 10,
    label: `${(i + 1) * 10}%`
  }))
];
</script>

<template>
  <div class="flex flex-col space-y-6 gap-4">
    <h1 class="text-3xl font-semibold text-gray-900">Settings</h1>
    <div class="bg-white rounded-2xl shadow-sm border border-gray-100 mb-8">
      <section class="border-b border-gray-100">
        <div class="px-8 py-6">
          <h2 class="text-lg font-medium text-gray-900">General</h2>
        </div>

        <div class="px-8 pb-6 space-y-6">
          <div class="flex items-center justify-between">
            <div>
              <p class="text-sm font-medium text-gray-700">Auto Start</p>
              <p class="text-xs text-gray-500 mt-1">
                Start the application automatically when you start your computer
              </p>
            </div>
            <Switch v-model="settings.autoStart" />
          </div>
          <div class="flex items-center justify-between">
            <div>
              <p class="text-sm font-medium text-gray-700">Auto Update</p>
              <p class="text-xs text-gray-500 mt-1">
                Keep the application up to date automatically
              </p>
            </div>
            <Switch v-model="settings.autoUpdate" />
          </div>
        </div>
      </section>
      <section>
        <div class="px-8 py-6">
          <h2 class="text-lg font-medium text-gray-900">Notifications</h2>
        </div>

        <div class="px-8 pb-6 space-y-6">
          <div class="flex items-center justify-between">
            <div>
              <p class="text-sm font-medium text-gray-700">Low battery</p>
              <p class="text-xs text-gray-500 mt-1">
                Sends a notification when the battery level is equal to or lower than the
                threshold value
              </p>
            </div>
            <div class="relative">
              <select
                class="h-9 min-w-24 text-sm text-end font-medium text-gray-700 bg-gray-50 border border-gray-200 rounded-lg pl-3 pr-2 outline-none appearance-none cursor-pointer transition-all"
                v-model="settings.lowBatteryThreshold"
              >
                <option
                  v-for="option in batteryThresholdOptions"
                  :key="option.value"
                  :value="option.value"
                  class="py-1 text-end cursor-pointer"
                >
                  {{ option.label }}
                </option>
              </select>
            </div>
          </div>
        </div>
      </section>
    </div>
  </div>
</template>

// crates/desktop/src/lib/views/settings-page.svelte
<script lang="ts">
  import { Card, Select, Switch } from "$lib/components/ui";
  import { settings, theme } from "$lib/stores";
  import type { ThemePreference } from "$lib/stores/theme.svelte";

  const THRESHOLDS = [
    { value: 0, label: "Off" },
    ...Array.from({ length: 9 }, (_, index) => ({
      value: (index + 1) * 10,
      label: `${(index + 1) * 10}%`
    }))
  ];

  const THEMES: { value: ThemePreference; label: string }[] = [
    { value: "system", label: "System" },
    { value: "light", label: "Light" },
    { value: "dark", label: "Dark" }
  ];

  const toggles = $derived([
    {
      key: "autoStart" as const,
      title: "Launch at sign-in",
      description: "Start winpods automatically when you sign in to Windows.",
      checked: settings.current.autoStart
    },
    {
      key: "autoUpdate" as const,
      title: "Automatic updates",
      description: "Download and install new versions in the background.",
      checked: settings.current.autoUpdate
    },
    {
      key: "earDetection" as const,
      title: "Automatic ear detection",
      description: "Pause audio when you take a bud out.",
      checked: settings.current.earDetection
    }
  ]);
</script>

<div class="mx-auto flex max-w-2xl flex-col gap-6">
  <div>
    <h1 class="text-xl font-semibold tracking-tight">Settings</h1>
  </div>

  <section class="flex flex-col gap-2">
    <h2 class="text-muted-foreground px-1 text-xs font-medium uppercase tracking-widest">
      General
    </h2>
    <Card flush class="divide-hairline divide-y">
      {#each toggles as toggle (toggle.key)}
        <div class="flex items-center justify-between gap-6 p-4">
          <div class="min-w-0">
            <p class="text-[13px] font-medium">{toggle.title}</p>
            <p class="text-muted-foreground mt-0.5 text-xs">{toggle.description}</p>
          </div>
          <Switch
            label={toggle.title}
            checked={toggle.checked}
            onchange={value => void settings.update({ [toggle.key]: value })}
          />
        </div>
      {/each}
    </Card>
  </section>

  <section class="flex flex-col gap-2">
    <h2 class="text-muted-foreground px-1 text-xs font-medium uppercase tracking-widest">
      Notifications
    </h2>
    <Card flush>
      <div class="flex items-center justify-between gap-6 p-4">
        <div class="min-w-0">
          <p class="text-[13px] font-medium">Low battery</p>
          <p class="text-muted-foreground mt-0.5 text-xs">
            Notify once when either bud reaches this level.
          </p>
        </div>
        <Select
          label="Low battery threshold"
          value={settings.current.lowBatteryThreshold}
          options={THRESHOLDS}
          onchange={value => void settings.update({ lowBatteryThreshold: value })}
        />
      </div>
    </Card>
  </section>

  <section class="flex flex-col gap-2">
    <h2 class="text-muted-foreground px-1 text-xs font-medium uppercase tracking-widest">
      Appearance
    </h2>
    <Card flush>
      <div class="flex items-center justify-between gap-6 p-4">
        <div class="min-w-0">
          <p class="text-[13px] font-medium">Theme</p>
          <p class="text-muted-foreground mt-0.5 text-xs">Follows Windows by default.</p>
        </div>
        <Select
          label="Theme"
          value={theme.preference}
          options={THEMES}
          onchange={value => theme.set(value)}
        />
      </div>
    </Card>
  </section>
</div>
