// crates/desktop/src/lib/components/ui/switch.svelte
<script lang="ts">
  import { cn } from "$lib/utils";

  interface Props {
    checked: boolean;
    disabled?: boolean;
    /** Accessible name, required because the switch renders no visible text of its own. */
    label: string;
    onchange?: (checked: boolean) => void;
    class?: string;
  }

  let { checked, disabled = false, label, onchange, class: className }: Props = $props();
</script>

<!--
  A plain button with role="switch" rather than a checkbox: it needs no form value, and this
  keeps the keyboard and screen reader behaviour correct without a headless dependency.
-->
<button
  type="button"
  role="switch"
  aria-checked={checked}
  aria-label={label}
  {disabled}
  onclick={() => onchange?.(!checked)}
  class={cn(
    "relative inline-flex h-[31px] w-[51px] shrink-0 cursor-pointer items-center rounded-full",
    "transition-colors duration-200 disabled:cursor-not-allowed disabled:opacity-40",
    checked ? "bg-battery-good" : "bg-border",
    className
  )}
>
  <span
    class={cn(
      "pointer-events-none block size-[27px] rounded-full bg-white shadow-sm",
      "transition-transform duration-200",
      checked ? "translate-x-[22px]" : "translate-x-[2px]"
    )}
  ></span>
</button>

// crates/desktop/src/components/Switch.vue
<template>
  <div class="inline-block my-2 mx-3">
    <label class="relative inline-block w-12 h-7">
      <input
        type="checkbox"
        :checked="modelValue"
        :disabled="disabled"
        @change="$emit('update:modelValue', ($event.target as HTMLInputElement).checked)"
        class="opacity-0 w-0 h-0"
      />
      <span
        class="absolute inset-0 rounded-full transition-colors duration-300 ease-in-out"
        :class="[
          modelValue ? 'bg-green-500' : 'bg-gray-300 bg-opacity-40',
          disabled ? 'cursor-not-allowed opacity-50' : 'cursor-pointer'
        ]"
      >
        <span
          class="absolute w-6 h-6 bg-white rounded-full shadow-md transition-transform duration-300 ease-in-out left-0.5 top-0.5"
          :class="modelValue ? 'transform translate-x-5' : ''"
        ></span>
      </span>
    </label>
  </div>
</template>

<script setup lang="ts">
interface SwitchProps {
  modelValue: boolean;
  disabled?: boolean;
}

defineProps<SwitchProps>();
defineEmits<{
  (e: "update:modelValue", value: boolean): void;
}>();
</script>
